// 给定默认语言，当没有适配的时候返回什么
const InitLanguage = 'zh';
// 翻译字典
const translateDictionary = {
  COMPANY: {
    en: 'Company',
    es: 'Empresa',
    fr: 'Entreprise',
    pt: 'Empresa',
    zh: '集团',
    'zh-tw': '公司',
    ja: '会社',
    th: 'บริษัท',
    ar: 'شركة',
    ko: '회사',
  },
  AC_LS_COPY: {
    en: 'Choose your location and language.',
    es: 'Elija su ubicación e idioma.',
    fr: 'Choisissez votre emplacement et votre langue.',
    pt: 'Escolha sua localização e idioma.',
    zh: '选择您的位置和语言。',
    'zh-tw': '選擇您的位置和語言。',
    ja: '場所と言語を選択してください。',
    th: 'เลือกตำแหน่งที่ตั้งและภาษาของคุณ',
    ar: 'اختر موقعك ولغتك.',
    ko: '지역과 언어를 선택하세요.',
  },
  AC_LS_COPY_ONLY_LANGUAGE: {
    en: 'Choose your location and language.',
    es: 'Elija su ubicación e idioma.',
    fr: 'Choisissez votre emplacement et votre langue.',
    pt: 'Escolha sua localização e idioma.',
    zh: '选择您的位置和语言。',
    'zh-tw': '選擇您的位置和語言。',
    ja: '場所と言語を選択してください。',
    th: 'เลือกตำแหน่งที่ตั้งและภาษาของคุณ',
    ar: 'اختر موقعك ولغتك.',
    ko: '지역과 언어를 선택하세요.',
  },
  AC_LS_OTHER_COUNTRY: {
    en: 'Other country or region',
    es: 'Otro país o región',
    fr: 'Autre pays ou région',
    pt: 'Outro país ou região',
    zh: '选择其他国家',
    'zh-tw': '選擇其他國家',
    ja: 'その他の国または地域',
    th: 'ประเทศหรือภูมิภาคอื่นๆ',
    ar: 'دولة أو منطقة أخرى',
    ko: '다른 국가 또는 지역',
  },
  LANGUAGE_NAME: {
    en: 'English',
    es: 'Español',
    fr: 'Français',
    pt: 'Português',
    zh: '简体中文',
    'zh-tw': '繁體中文',
    ja: '日本語',
    th: 'ภาษาไทย',
    ar: 'العربية',
    ko: '한국어',
  },
  NO_ITEMS_FOUND: {
    en: 'No items found.',
    es: 'No se han encontrado artículos.',
    fr: 'Aucun élément trouvé.',
    pt: 'Nenhum item encontrado.',
    zh: '未找到任何项目。',
    'zh-tw': '找不到任何項目。',
    ja: 'アイテムが見つかりませんでした。',
    th: 'ไม่พบรายการใดๆ',
    ar: 'لم يتم العثور على أي عناصر.',
    ko: '항목을 찾을 수 없습니다.',
  },
  SAVE: {
    en: 'Save',
    es: 'Guardar',
    fr: 'Enregistrer',
    pt: 'Salvar',
    zh: '保存',
    'zh-tw': '儲存',
    ja: '保存',
    th: 'บันทึก',
    ar: 'حفظ',
    ko: '저장',
  },
  LEARN_MORE: {
    en: 'Learn more',
    es: 'Más información',
    fr: 'En savoir plus',
    pt: 'Saiba mais',
    zh: '了解更多',
    'zh-tw': '了解更多',
    ja: '詳しくはこちら',
    th: 'เรียนรู้เพิ่มเติม',
    ar: 'معرفة المزيد',
    ko: '자세히 알아보기',
  },
  NO_FAQ_ITEMS_AVAILABLE: {
    en: 'No FAQ items available.',
    es: 'No hay preguntas frecuentes disponibles.',
    fr: 'Aucun élément de la FAQ disponible.',
    pt: 'Nenhum item de FAQ disponível.',
    zh: '暂无常见问题。',
    'zh-tw': '沒有可用的常見問題項目。',
    ja: 'FAQ項目はありません。',
    th: 'ไม่มีรายการคำถามที่พบบ่อย',
    ar: 'لا توجد عناصر في الأسئلة الشائعة.',
    ko: 'FAQ 항목이 없습니다.',
  },
  SUPPORT: {
    en: 'Support',
    es: 'Soporte',
    fr: 'Assistance',
    pt: 'Suporte',
    zh: '支持',
    'zh-tw': '支援',
    ja: 'サポート',
    th: 'ฝ่ายสนับสนุน',
    ar: 'الدعم',
    ko: '지원',
  },
  COMPARE: {
    en: 'Compare',
    es: 'Comparar',
    fr: 'Comparer',
    pt: 'Comparar',
    zh: '比较',
    'zh-tw': '比較',
    ja: '比較する',
    th: 'เปรียบเทียบ',
    ar: 'مقارنة',
    ko: '비교',
  },
  SEE_DETAILS: {
    en: 'See details',
    es: 'Ver detalles',
    fr: 'Voir les détails',
    pt: 'Ver detalhes',
    zh: '查看详情',
    'zh-tw': '查看詳情',
    ja: '詳細を見る',
    th: 'ดูรายละเอียด',
    ar: 'عرض التفاصيل',
    ko: '자세히 보기',
  },
  KEY_INFORMATION: {
    en: 'Key Information',
    es: 'Información clave',
    fr: 'Informations clés',
    pt: 'Informações principais',
    zh: '关键信息',
    'zh-tw': '重要資訊',
    ja: '重要情報',
    th: 'ข้อมูลสำคัญ',
    ar: 'معلومات أساسية',
    ko: '핵심 정보',
  },
  JOB_TITLE: {
    en: 'Job Title',
    es: 'Título del puesto',
    fr: 'Intitulé du poste',
    pt: 'Cargo',
    zh: '职位',
    'zh-tw': '職稱',
    ja: '役職名',
    th: 'ตำแหน่งงาน',
    ar: 'المسمى الوظيفي',
    ko: '직책',
  },
  WORK_LOCATION: {
    en: 'Work Location',
    es: 'Lugar de trabajo',
    fr: 'Lieu de travail',
    pt: 'Local de trabalho',
    zh: '工作地点',
    'zh-tw': '工作地點',
    ja: '勤務地',
    th: 'สถานที่ทำงาน',
    ar: 'مكان العمل',
    ko: '근무지',
  },
  JOB_TYPES: {
    en: 'Job Types',
    es: 'Tipos de puesto',
    fr: "Types d'emploi",
    pt: 'Tipos de vaga',
    zh: '职位类型',
    'zh-tw': '職務類型',
    ja: '雇用形態',
    th: 'ประเภทงาน',
    ar: 'أنواع الوظائف',
    ko: '채용 유형',
  },
  KEY_FACTS: {
    en: 'Key Facts',
    es: 'Datos clave',
    fr: 'Faits clés',
    pt: 'Principais fatos',
    zh: '关键事实',
    'zh-tw': '重點資訊',
    ja: '主な事項',
    th: 'ข้อเท็จจริงสำคัญ',
    ar: 'حقائق أساسية',
    ko: '주요 사실',
  },
  QTY: {
    en: 'Qty:',
    es: 'Cant.:',
    fr: 'Qté :',
    pt: 'Qtd:',
    zh: '数量：',
    'zh-tw': '數量：',
    ja: '数量:',
    th: 'จำนวน:',
    ar: 'الكمية:',
    ko: '수량:',
  },
  ADD_TO_CART: {
    en: 'Add to Cart',
    es: 'Añadir al carrito',
    fr: 'Ajouter au panier',
    pt: 'Adicionar ao carrinho',
    zh: '加入购物车',
    'zh-tw': '加入購物車',
    ja: 'カートに追加',
    th: 'เพิ่มลงในตะกร้า',
    ar: 'أضف إلى السلة',
    ko: '장바구니에 담기',
  },
  OUT_OF_STOCK: {
    en: 'Out of stock',
    es: 'Agotado',
    fr: 'Rupture de stock',
    pt: 'Fora de estoque',
    zh: '缺货',
    'zh-tw': '缺貨',
    ja: '在庫切れ',
    th: 'สินค้าหมด',
    ar: 'غير متوفر',
    ko: '품절',
  },
  ITEM_ADDED_TO_YOUR_CART: {
    en: 'Item added to your cart',
    es: 'Artículo añadido a tu carrito',
    fr: 'Article ajouté à votre panier',
    pt: 'Item adicionado ao seu carrinho',
    zh: '商品已加入购物车',
    'zh-tw': '商品已加入購物車',
    ja: '商品をカートに追加しました。',
    th: 'รายการถูกเพิ่มลงในตะกร้าของคุณ',
    ar: 'تمت إضافة العنصر إلى سلتك',
    ko: '상품이 장바구니에 담겼습니다.',
  },
  MODEL: {
    en: 'Model:',
    es: 'Modelo:',
    fr: 'Modèle :',
    pt: 'Modelo:',
    zh: '型号：',
    'zh-tw': '型號：',
    ja: 'モデル:',
    th: 'รุ่น:',
    ar: 'الطراز:',
    ko: '모델:',
  },
  FILTERS: {
    en: 'FILTERS',
    es: 'FILTROS',
    fr: 'FILTRES',
    pt: 'FILTROS',
    zh: '筛选',
    'zh-tw': '篩選',
    ja: 'フィルター',
    th: 'ตัวกรอง',
    ar: 'المرشحات',
    ko: '필터',
  },
  AWARD_WINNING: {
    en: 'award winning',
    es: 'galardonado',
    fr: 'primé',
    pt: 'premiado',
    zh: '屡获殊荣',
    'zh-tw': '屢獲殊榮',
    ja: '受賞歴あり',
    th: 'ได้รับรางวัล',
    ar: 'حائز على جوائز',
    ko: '수상 경력',
  },
  FAQ: {
    en: 'FAQ',
    es: 'Preguntas frecuentes',
    fr: 'FAQ',
    pt: 'FAQ',
    zh: '常见问题',
    'zh-tw': '常見問題',
    ja: 'よくある質問',
    th: 'คำถามที่พบบ่อย',
    ar: 'الأسئلة الشائعة',
    ko: '자주 묻는 질문',
  },
  SPECS: {
    en: 'SPECS',
    es: 'ESPECIFICACIONES',
    fr: 'SPÉCIFICATIONS',
    pt: 'ESPECIFICAÇÕES',
    zh: '规格',
    'zh-tw': '規格',
    ja: '仕様',
    th: 'สเปค',
    ar: 'المواصفات',
    ko: '사양',
  },
  WHERE_TO_BUY: {
    en: 'Where to buy',
    es: 'Dónde comprar',
    fr: 'Où acheter',
    pt: 'Onde comprar',
    zh: '购买地点',
    'zh-tw': '哪裡購買',
    ja: '購入先',
    th: 'ซื้อที่ไหน',
    ar: 'أين تشتري',
    ko: '구매처 안내',
  },
  IN_STOCK: {
    en: 'In Stock',
    es: 'En stock',
    fr: 'En stock',
    pt: 'Em estoque',
    zh: '有现货',
    'zh-tw': '有現貨',
    ja: '在庫あり',
    th: 'มีสินค้า',
    ar: 'متوفر',
    ko: '재고 있음',
  },
  VIEW_CART: {
    en: 'View cart',
    es: 'Ver carrito',
    fr: 'Voir le panier',
    pt: 'Ver carrinho',
    zh: '查看购物车',
    'zh-tw': '查看購物車',
    ja: 'カートを見る',
    th: 'ดูตะกร้าสินค้า',
    ar: 'عرض السلة',
    ko: '장바구니 보기',
  },
  PROCEED_TO_CHECKOUT: {
    en: 'Proceed to checkout',
    es: 'Proceder al pago',
    fr: 'Passer à la caisse',
    pt: 'Finalizar compra',
    zh: '前往结算',
    'zh-tw': '前往結帳',
    ja: 'レジに進む',
    th: 'ไปยังการชำระเงิน',
    ar: 'المتابعة إلى الدفع',
    ko: '결제하기',
  },
  OVERVIEW: {
    en: 'Overview',
    es: 'Resumen',
    fr: 'Aperçu',
    pt: 'Visão geral',
    zh: '概览',
    'zh-tw': '概覽',
    ja: '概要',
    th: 'ภาพรวม',
    ar: 'نظرة عامة',
    ko: '개요',
  },
  DISCOVER_MORE: {
    en: 'Discover more',
    es: 'Descubre más',
    fr: 'Découvrez-en plus',
    pt: 'Descubra mais',
    zh: '探索更多',
    'zh-tw': '發現更多',
    ja: 'さらに詳しく',
    th: 'ค้นพบเพิ่มเติม',
    ar: 'اكتشف المزيد',
    ko: '더 알아보기',
  },
  COMPARE_TV_MODELS: {
    en: 'Compare TV Models',
    es: 'Comparar modelos de TV',
    fr: 'Comparer les modèles de téléviseurs',
    pt: 'Comparar modelos de TV',
    zh: '比较电视型号',
    'zh-tw': '比較電視型號',
    ja: 'テレビモデルを比較',
    th: 'เปรียบเทียบรุ่นทีวี',
    ar: 'قارن طرازات التلفزيون',
    ko: 'TV 모델 비교',
  },
  COMPARE_FEATURES_AND_FIND_YOUR_FIT: {
    en: 'Compare features and find your fit.',
    es: 'Compara características y encuentra el que más te conviene.',
    fr: 'Comparez les caractéristiques et trouvez le modèle qui vous convient.',
    pt: 'Compare recursos e encontre o ideal para você.',
    zh: '比较功能，找到适合你的机型。',
    'zh-tw': '比較功能，找到適合您的機型。',
    ja: '機能を比較してあなたに合うものを見つけましょう。',
    th: 'เปรียบเทียบคุณสมบัติและค้นหาที่เหมาะกับคุณ',
    ar: 'قارن الميزات واعثر على الأنسب لك.',
    ko: '기능을 비교하여 나에게 맞는 제품을 찾아보세요.',
  },
  CONTINUE: {
    en: 'Continue',
    es: 'Continuar',
    fr: 'Continuer',
    pt: 'Continuar',
    zh: '继续',
    'zh-tw': '繼續',
    ja: '続行',
    th: 'ดำเนินการต่อ',
    ar: 'متابعة',
    ko: '계속',
  },
  READ_NOW: {
    en: 'Read Now',
    es: 'Leer Ahora',
    fr: 'Lire Maintenant',
    pt: 'Ler Agora',
    zh: '立即阅读',
    'zh-tw': '立即閱讀',
    ja: '今すぐ読む',
    th: 'อ่านเลย',
    ar: 'اقرأ الآن',
    ko: '지금 읽기',
  },
};
/**
 * 获取指定键和语言对应的翻译
 * @param {string} key - 字典中的键名（如 'Company'）
 * @param {string} lang - 语言代码（如 'en', 'zh', 'fr'），不区分大小写
 * @returns {string} 翻译后的文本，若未找到则返回原 key 或空字符串
 */
function translate(key, lang) {
  // 参数校验
  if (!key || typeof key !== 'string') {
    return '';
  }

  if (!lang || typeof lang !== 'string') {
    return key; // 降级返回原 key
  }

  const normalizedLang = lang.toLowerCase();
  const entry = translateDictionary[key];

  // 若存在该条目
  if (entry) {
    if (entry[normalizedLang]) {
      return entry[normalizedLang];
    }
    if (entry[InitLanguage]) {
      return entry[InitLanguage];
    }
    if (entry.en) {
      return entry.en;
    }
    const firstLang = Object.values(entry)[0];
    if (firstLang) {
      return firstLang;
    }
  }

  // 完全找不到时，返回原 key 并给出警告
  // eslint-disable-next-line no-console
  console.warn(`translate: 未找到键 "${key}" 或语言 "${lang}" 的翻译`);
  return key;
}

export default translate;
