// eslint-disable-next-line import/prefer-default-export
export const MOCK_DATA = {
  total: 120,
  list: [
    {
      title: '海信激光电视',
      type: '产品',
      category: '智慧生活',
      thumbnail: '/content/dam/hisense-dev/cn/tv.png',
      mediaType: 'image',
      file: '/content/dam/xxx.pdf',
      videoUrl: '',
      publishDate: '2025-11-07',
      location: '青岛',
    },
    {
      title: '海信',
      type: '商标',
      category: null,
      thumbnail: '/content/dam/hisense-dev/cn/logo.png',
      mediaType: 'image',
      file: '/content/dam/xxx.pdf',
      videoUrl: '',
      publishDate: '2025-11-07',
      location: '青岛',
    },
    {
      title: '海信激光电视',
      type: '产品',
      category: '智慧能源',
      thumbnail: '/content/dam/hisense-dev/cn/tv.png',
      mediaType: 'image',
      file: '/content/dam/xxx.pdf',
      videoUrl: '',
      publishDate: '2025-11-07',
      location: '青岛',
    },
    {
      title: '海信激光电视',
      type: '产品',
      category: '半导体',
      thumbnail: '/content/dam/hisense-dev/cn/tv.png',
      mediaType: 'image',
      file: '/content/dam/xxx.pdf',
      videoUrl: '',
      publishDate: '2025-11-07',
      location: '青岛',
    },
    {
      title: '海信激光电视',
      type: '活动',
      category: '展会峰会',
      thumbnail: '/content/dam/hisense-dev/cn/tv.png',
      mediaType: 'image',
      file: '/content/dam/xxx.pdf',
      videoUrl: '',
      publishDate: '2025-11-07',
      location: '青岛',
    },
    {
      title: '海信激光电视',
      type: '产品',
      category: '智慧生活',
      thumbnail: '/content/dam/hisense-dev/cn/tv.png',
      mediaType: 'image',
      file: '/content/dam/xxx.pdf',
      videoUrl: '',
      publishDate: '2025-11-07',
      location: '青岛',
    },
    {
      title: '海信激光电视',
      type: '产品',
      category: '智慧生活',
      thumbnail: '/content/dam/hisense-dev/cn/tv.png',
      mediaType: 'image',
      file: '/content/dam/xxx.pdf',
      videoUrl: '',
      publishDate: '2025-11-07',
      location: '青岛',
    },
    {
      title: '海信激光电视',
      type: '产品',
      category: '智慧生活',
      thumbnail: '/content/dam/hisense-dev/cn/tv.png',
      mediaType: 'image',
      file: '/content/dam/xxx.pdf',
      videoUrl: '',
      publishDate: '2025-11-07',
      location: '青岛',
    },
    {
      title: '海信激光电视',
      type: '产品',
      category: '智慧生活',
      thumbnail: '/content/dam/hisense-dev/cn/tv.png',
      mediaType: 'image',
      file: '/content/dam/xxx.pdf',
      videoUrl: '',
      publishDate: '2025-11-07',
      location: '青岛',
    },
    {
      title: '海信激光电视',
      type: '产品',
      category: '智慧生活',
      thumbnail: '/content/dam/hisense-dev/cn/tv.png',
      mediaType: 'image',
      file: '/content/dam/xxx.pdf',
      videoUrl: '',
      publishDate: '2025-11-07',
      location: '青岛',
    },
    {
      title: '海信激光电视',
      type: '产品',
      category: '智慧生活',
      thumbnail: '/content/dam/hisense-dev/cn/tv.png',
      mediaType: 'image',
      file: '/content/dam/xxx.pdf',
      videoUrl: '',
      publishDate: '2025-11-07',
      location: '青岛',
    },
    {
      title: '海信激光电视',
      type: '产品',
      category: '智慧生活',
      thumbnail: '/content/dam/hisense-dev/cn/tv.png',
      mediaType: 'image',
      file: '/content/dam/xxx.pdf',
      videoUrl: '',
      publishDate: '2025-11-07',
      location: '青岛',
    },
  ],
};
